---
title: "CI: feature norming analysis"
# output: html_document
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data import, include=FALSE}
library(cowplot)
library(tidyverse)
library(here)

df_import = read_csv(here("data","01_norming","02_main","01_ListFeature-norming","data.csv")) %>% 
  # exclude test
  # weird filter property that it will exclude NAs
  filter(is.na(comments) | comments != "TEST")
```

```{r botresponse, include=FALSE}
ggplot(df_import,aes(x=str_to_lower(botresponse))) +
  geom_histogram(stat="count")
```

```{r responses to postquestionnaire, eval=FALSE, fig.height=1.5, fig.width=4, include=FALSE}
# check responses to post questionnaire, which participants I need to exclude (e.g., HitCorrect and NativeLanguage)
df_hitcorrect = df_import %>% 
  mutate_at(vars(HitCorrect),
            funs(ifelse(HitCorrect==0,"no",
                        ifelse(HitCorrect==404,"confused","yes"))))

ggplot(df_hitcorrect,aes(x=HitCorrect)) +
  geom_bar(width = .5,
           fill = "orange") +
  xlab("did you do the hit correctly")

# languages
unique(df_import$languages)

# comments
unique(df_import$comments)
```

```{r create main data frame, message=FALSE, include=FALSE}

df_clean = df_import %>% 
  # exclude multiple submissions
  arrange(startTime) %>% 
  distinct(anon_worker_id,trial_number, .keep_all = TRUE) %>% 
  # exclude participants who didn't answer the bot task (probably bots which hacked javascript code), if necessary
  # filter(botresponse=="") %>% 
  # exclude participants who didn't pass control objects (nonce words)
  mutate(control = ifelse((question == "wobs" | question == "ebbler" | question == "briggle" | question == "florbs"),T,F)) %>%  
  mutate(correct_controls = ifelse(control & obj_unknown,T,F)) %>% 
  group_by(anon_worker_id) %>% 
  mutate(pass_controls = ifelse(sum(correct_controls)<2,F,T)) %>% 
  filter(pass_controls) %>% 
  # exclude participants who rated more than 8 as "object unknown"
  # excludes 2 workers
  filter(!sum(obj_unknown)>8) %>% 
  ungroup()

# number of participants before exclusion (40)
length(unique(df_import$anon_worker_id))
# number of participants after exclusion (38)
length(unique(df_clean$anon_worker_id))


df = df_clean %>%
  filter(!control) %>% 
  select(feature1,feature2,feature3,obj_unknown,question,anon_worker_id) %>% 
  mutate_at(vars(feature1,feature2,feature3),funs(str_to_lower(.)))
```


### About the participants (after exclusion)

```{r subj, echo=FALSE, fig.height=6, fig.width=8, message=FALSE, warning=FALSE}
# other info
engl_spellings = c("english", "englis", "eng", "engilsh")

df_subj = df_clean %>% 
  select(age,gender,education,languages,enjoyment,timeSpent,HitCorrect,comments,anon_worker_id) %>% 
  distinct() %>% 
  mutate_at(vars(languages), funs(str_to_lower(.))) %>% 
  mutate_at(vars(languages), funs(ifelse(. %in% engl_spellings, "english", .))) %>% 
  mutate(lang=ifelse(languages == "english","english","other")) %>% 
  mutate_at(vars(age), funs(as.integer(.))) %>% 
  mutate_at(vars(enjoyment), 
            funs(ifelse(.==1,"average",
                        ifelse(.==2,"awesome","other")))) %>% 
  mutate(edu = ifelse(str_detect(education,"high_school"),"High School",
                      ifelse(str_detect(education,"college"),"College","Higher"))) %>% 
  mutate_at(vars(edu), funs(fct_relevel(.,"High School", "College", "Higher")))


mean_age = round(mean(df_subj$age),digits = 1)
p_age = ggplot(df_subj,aes(x=age)) +
  geom_bar(width = .5,
           fill = "orange") +
  geom_vline(xintercept= mean_age) +
  scale_x_continuous(breaks=c(25,50,75,mean_age))

p_gen = ggplot(df_subj,aes(x=gender)) +
  geom_bar(width = .5,
           fill = "orange")

p_edu = ggplot(df_subj,aes(x=edu)) +
  geom_bar(width = .5,
           fill = "orange") +
  xlab("education")
  # theme(axis.text.x = element_text(angle = 25, hjust = 1))

p_lang = ggplot(df_subj,aes(x=lang)) +
  geom_bar(width = .5,
           fill = "orange") +
  xlab("language")
  # theme(axis.text.x = element_text(angle=45,hjust=1))

p_enj = ggplot(df_subj,aes(x=enjoyment)) +
  geom_bar(width = .5,
           fill = "orange")

mean_time = round(mean(df_subj$timeSpent), digits = 1)
median_time = round(median(df_subj$timeSpent), digits = 1)
p_time = ggplot(df_subj,aes(x=timeSpent)) +
  geom_histogram(fill = "orange") +
  geom_vline(xintercept=mean_time) +
  geom_vline(xintercept=median_time,linetype="dashed") +
  scale_x_continuous(breaks=c(median_time,mean_time,floor(0),floor(10),floor(25),floor(20))) +
  xlab("time spent")

plot_grid(p_age,p_gen,p_edu,p_lang,p_enj,p_time, labels = "AUTO", ncol = 2, align = 'v')

```

### Objects which were rated unknown

```{r obj_unknown, echo=FALSE, fig.height=3, fig.width=4.5}
ggplot(df[df$obj_unknown==TRUE,],aes(x=question)) +
  geom_bar(width = 0.5,
           fill = "orange") +
  theme(axis.text.x = element_text(angle=45,hjust=1)) +
  xlab("object") +
  ylab("clicked object unknown\n(total number)")
```


```{r df color features, include=FALSE}

# color_list = c("bright", "brightly", "clear", "color", "colored", "colorful", "colour", "multicolored", "black", "blue", "brown", "green", "orange", "pink", "red", "white", "yellow")

color_list = c("black", "blackish", "blue", "brown", "green", "orange", "pink", "pink\\n", "red", "white", "yellow")

white = c("snowman", "swan", "toilet paper", "egg")
orange = c("basketball", "pumpkin", "carrot", "traffic cone")
pink = c("flamingo", "piggy bank", "cotton candy", "pig")
yellow = c("banana", "taxi", "corn", "rubber duck")
red = c("tomato", "lobster", "strawberry", "fire extinguisher")
green = c("broccoli", "lettuce", "zucchini", "cactus", "pickle")

cd_list = c("snowman",
	"swan",
	"toilet paper",
	"egg",
	"basketball",
	"pumpkin",
	"carrot",
	"traffic cone",
	"flamingo",
	"piggy bank",
	"cotton candy",
	"pig",
	"banana",
	"taxi",
	"corn",
	"rubber duck",
	"tomato",
	"lobster",
	"strawberry",
	"fire extinguisher",
	"broccoli",
	"lettuce",
	"zucchini",
	"cactus",
	"pickle")

df_cat = df %>%
  filter(obj_unknown==FALSE) %>% 
  # mutate(f1_cat = ifelse(sum(str_detect(feature1,color_list)) >= 1, T, F)) %>% 
  mutate(color = case_when(question %in% white ~ "white",
                           question %in% orange ~ "orange",
                           question %in% pink ~ "pink",
                           question %in% yellow ~ "yellow",
                           question %in% red ~ "red",
                           question %in% green ~ "green", 
                           TRUE ~ "no-cd")) %>% 
  gather(feature_pos,feature_utt,feature1,feature2,feature3) %>% 
  mutate(color_mention = ifelse(feature_utt %in% color_list, T, F)) %>% 
  mutate(cd = ifelse(question %in% cd_list, T, F))

df_plot = df_cat %>% 
  select(-obj_unknown)

```

## Plot proportion of color mention (only cd)

#### Only first feature

```{r plot first feature cdonly, echo=FALSE, fig.height=6, fig.width=8}
df_plot_f1 = df_plot %>% 
  # gather(feature_pos,color_mention,f1_cat,f2_cat,f3_cat) %>% 
  mutate_at(vars(color_mention),funs(as.integer(.))) %>% 
  filter(feature_pos=="feature1")

ggplot(df_plot_f1[df_plot_f1$cd==T,],aes(x=reorder(reorder(question,color_mention),cd), y=color_mention, fill=cd)) +
  facet_wrap(vars(color), scale="free_x") +
  stat_summary(fun.y = "mean",
               geom = "bar") +
  stat_summary(fun.data = "mean_cl_boot",
               geom = "linerange",
               color = "darkgrey") +
  geom_hline(yintercept = 0.5,
             linetype = "dashed",
             color = "grey") +
  theme(legend.position="none") +
  theme(axis.text.x = element_text(angle = 30, hjust=1)) +
  scale_fill_manual(values=c("#7CB637")) +
  xlab("objects facetted by intended typical color") +
  ylab("proportion of color mention in first feature")

# ggsave(here("writing", "QP1", "img", "norming1_results.pdf"), width=7, height=6)
```

#### All features

```{r plot all features cdonly new, echo=FALSE, fig.height=6, fig.width=8}

# library(bootstrap)
# theta <- function(x,xdata,na.rm=T) {mean(xdata[x],na.rm=na.rm)}
# ci.low <- function(x,na.rm=T) {
#   mean(x,na.rm=na.rm) - quantile(bootstrap(1:length(x),1000,theta,x,na.rm=na.rm)$thetastar,.025,na.rm=na.rm)}
# ci.high <- function(x,na.rm=T) {
#   quantile(bootstrap(1:length(x),1000,theta,x,na.rm=na.rm)$thetastar,.975,na.rm=na.rm) - mean(x,na.rm=na.rm)}

df_plot_allf = df_plot %>%
  mutate_at(vars(color_mention),funs(as.integer(.))) %>%
  filter(cd==T)
  # group_by(question, add=TRUE) %>% 
  # mutate(mean_colprop = mean(color_mention),
  #        ci_min = mean_colprop - ci.low(color_mention),
  #        ci_max = mean_colprop + ci.high(color_mention)) %>% 
  # ungroup()

ggplot(df_plot_allf,aes(x=reorder(reorder(question,color_mention),cd), y=color_mention, fill=cd)) +
  facet_wrap(vars(color), scale="free") +
  stat_summary(fun.y = "mean",
               geom = "bar") +
  stat_summary(fun.data = "mean_cl_boot",
               geom = "linerange",
               color = "darkgrey") +
  # is here identical to mean_cl_boot
  # geom_errorbar(aes(ymin=ci_min, ymax=ci_max),
  #               color = "darkgrey",
  #               width = 0.5) +
  geom_hline(yintercept = 0.333,
             linetype = "dashed",
             color = "grey") +
  theme(legend.position="none") +
  theme(axis.text.x = element_text(angle = 30, hjust=1)) +
  scale_fill_manual(values=c("#7CB637")) +
  xlab("objects facetted by intended typical color") +
  ylab("proportion of color mention across features")
```

```{r plot all features cdonly old, echo=FALSE, fig.height=6, fig.width=8}
df_plot_allf = df_plot %>% 
  mutate_at(vars(color_mention),funs(as.integer(.)))
  # filter(feature_pos=="feature1")

ggplot(df_plot_allf[df_plot_allf$cd==T,],aes(x=reorder(reorder(question,color_mention),cd), y=color_mention, fill=cd)) +
  facet_wrap(vars(color), scale="free") +
  stat_summary(fun.y = "mean",
               geom = "bar") +
  stat_summary(fun.data = "mean_cl_boot",
               geom = "linerange",
               color = "darkgrey") +
  geom_hline(yintercept = 0.333,
             linetype = "dashed",
             color = "grey") +
  theme(legend.position="none") +
  theme(axis.text.x = element_text(angle = 30, hjust=1)) +
  scale_fill_manual(values=c("#7CB637")) +
  xlab("objects facetted by intended typical color") +
  ylab("proportion of color mention across features")
```

## Plot proportion of color mention (cd & non cd)

#### Only first feature

```{r plot first feature all, echo=FALSE, fig.height=7, fig.width=12}

ggplot(df_plot_f1,aes(x=reorder(reorder(question,color_mention),cd), y=color_mention, fill=cd)) +
  stat_summary(fun.y = "mean",
               geom = "bar") +
  stat_summary(fun.data = "mean_cl_boot",
               geom = "linerange",
               color = "darkgrey") +
  geom_hline(yintercept = 0.5,
             linetype = "dashed",
             color = "grey") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  theme(legend.position="top") +
  scale_fill_manual(values=c("#E6AB02", "#7CB637"), name = "presumably", labels = c("non-color-diagnostic", "color-diagnostic")) +
  # scale_fill_discrete(name = "Dose", labels = c("A", "B")) +
  xlab("objects") +
  ylab("proportion of color mention\nin first feature")

# ggsave(here("writing", "QP1", "img", "norming1_resultsoverall.pdf"), width=9.5, height=5)
```

#### All features

```{r plot all features all, echo=FALSE, fig.height=7, fig.width=12}

ggplot(df_plot_allf,aes(x=reorder(reorder(question,color_mention),cd), y=color_mention, fill=cd)) +
  stat_summary(fun.y = "mean",
               geom = "bar") +
  stat_summary(fun.data = "mean_cl_boot",
               geom = "linerange",
               color = "darkgrey") +
  geom_hline(yintercept = 0.5,
             linetype = "dashed",
             color = "grey") +
  theme(axis.text.x = element_text(angle = 30, hjust=1)) +
  theme(legend.position="top") +
  scale_fill_manual(values=c("#E6AB02", "#7CB637")) +
  xlab("objects") +
  ylab("proportion of color mention in all features")
```

## Color utterances for each item (split by cd and non-cd)

#### Only first feature

```{r first feature colors, echo=FALSE, fig.height=10, fig.width=10}
# CD, color
df_cd_coloronly = df_plot_f1 %>% 
  filter(cd) %>% 
  filter(as.logical(color_mention))

ggplot(df_cd_coloronly, aes(x=feature_utt)) +
  geom_bar(stat = "count",
           fill = "#7CB637",
           width = 0.5) +
  ggtitle("Presumably color diagnostic") +
  facet_wrap(vars(question), scale="free_x") +
  theme(plot.title = element_text(size=15)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlab("colors mentioned in first feature for each object") +
  ylab("total number of color being mentioned in first feature")

# no CD, color
df_nocd_coloronly = df_plot_f1 %>% 
  filter(!cd) %>% 
  filter(as.logical(color_mention))

ggplot(df_nocd_coloronly, aes(x=feature_utt)) +
  geom_bar(stat="count",
           fill = "#E6AB02",
           width = 0.5) +
  ggtitle("Presumably non color diagnostic") +
  facet_wrap(vars(question), scale="free_x") +
  theme(plot.title = element_text(size=15)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlab("colors mentioned in first feature for each object") +
  ylab("total number of color being mentioned in first feature")
```

#### All features

```{r all features colors, echo=FALSE, fig.height=10, fig.width=10}
# CD, color
df_cd_coloronly = df_plot %>% 
  filter(cd) %>% 
  filter(color_mention)

ggplot(df_cd_coloronly, aes(x=feature_utt)) +
  geom_bar(stat = "count",
           fill = "#7CB637",
           width = 0.5) +
  ggtitle("Presumably color diagnostic") +
  facet_wrap(vars(question), scale="free_x") +
  theme(plot.title = element_text(size=15)) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlab("colors mentioned in all features for each object") +
  ylab("total number of color being mentioned in all features")

# ggsave(here("writing", "QP1", "img", "norming1_resultscolorcd.pdf"), width=10, height=11)

# no CD, color
df_nocd_coloronly = df_plot %>% 
  filter(!cd) %>% 
  filter(color_mention)

ggplot(df_nocd_coloronly, aes(x=feature_utt)) +
  geom_bar(stat="count",
           fill = "#E6AB02",
           width = 0.5) +
  ggtitle("Presumably non color diagnostic") +
  facet_wrap(vars(question), scale="free_x") +
  theme(plot.title = element_text(size=15)) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlab("colors mentioned in first feature for each object") +
  ylab("total number of color being mentioned in all features")

# ggsave(here("writing", "QP1", "img", "norming1_resultscolornoncd.pdf"), width=10, height=11)

df_nocd_coloronly %>% 
  filter(question == "bell pepper") %>% 
  ggplot(., aes(x=feature_utt)) +
    geom_bar(stat="count",
             fill = "#E6AB02",
             width = 0.5) +
    ggtitle("Presumably non color diagnostic") +
    facet_wrap(vars(question), scale="free_x") +
    theme(plot.title = element_text(size=15)) +
    # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    xlab("colors mentioned in first feature for each object") +
    ylab("total number of color being\nmentioned in all features")

ggsave(here("writing", "QP1", "img", "norming1_resultscolorbellpepper.pdf"), width=5, height=3)
```


## Find typos

```{r find typos, message=FALSE, include=FALSE}

freq_feature_list = df_plot %>% 
  filter(!color_mention) %>% 
  arrange(feature_utt) %>% 
  group_by(feature_utt) %>% 
  summarize(n=n()) %>% 
  filter(n>=2) 

# did I miss any color utterances?
freq_feature_list$feature_utt

# CD, no color
df_cd_nocol_infreq = df_plot %>% 
  filter(cd) %>% 
  filter(!color_mention & !(feature_utt %in% freq_feature_list$feature_utt))

table(arrange(df_cd_nocol_infreq,feature_utt)$feature_utt)

# ggplot(df_cd_nocol_infreq, aes(x=feature_utt)) +
#   geom_bar(stat="count") +
#   facet_wrap(vars(question), scale="free") +
#   theme(axis.text.x = element_text(angle = 45, hjust = 1))

# no CD, no color
df_nocd_nocol_infreq = df_plot %>% 
  filter(!cd) %>% 
  filter(!color_mention & !(feature_utt %in% freq_feature_list$feature_utt))

table(arrange(df_nocd_nocol_infreq,feature_utt)$feature_utt)

# ggplot(df_nocd_nocol_infreq, aes(x=feature_utt)) +
#   geom_bar(stat="count") +
#   facet_wrap(vars(question), scale="free") +
#   theme(axis.text.x = element_text(angle = 45, hjust = 1))
```











